# Generated by Django 5.2.11 on 2026-02-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('section_name', models.CharField(max_length=5)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.class')),
            ],
        ),
    ]
