# Generated by Django 5.2.11 on 2026-02-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
