# Generated by Django 5.2.11 on 2026-02-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subject')),
            ],
        ),
    ]
