# Generated by Django 5.2.11 on 2026-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_facultyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyassignment',
            name='is_class_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='facultyassignment',
            unique_together={('faculty', 'subject', 'class_obj', 'section')},
        ),
    ]
