# Generated by Django 5.2.11 on 2026-02-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_facultyassignment_is_class_incharge_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_name', 'class_obj')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_code',
        ),
    ]
