# Generated by Django 5.2.11 on 2026-02-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.facultyassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.student')),
            ],
            options={
                'unique_together': {('student', 'assignment', 'date')},
            },
        ),
    ]
