# Generated by Django 5.2.11 on 2026-02-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.FloatField()),
                ('external_marks', models.FloatField()),
                ('total_marks', models.FloatField(editable=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
    ]
