# Generated by Django 5.2.11 on 2026-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_exam_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(fields=('subject', 'class_obj', 'section'), name='unique_subject_per_class'),
        ),
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'class_obj', 'section'), name='faculty_one_subject_per_class'),
        ),
        migrations.AddConstraint(
            model_name='facultyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_class_incharge', True)), fields=('class_obj', 'section'), name='only_one_class_incharge_per_section'),
        ),
    ]
